
default: &default
  adapter: mysql2
  database: blog
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: password

development:
  <<: *default


test:
  <<: *default


production:
  <<: *default

